### PR TITLE
move from deprecated setup.py to pyproject.toml

### PR DESCRIPTION
**Pull request by noraj**
setup.py is deprecated, several PEP describe how to implement pyproject.toml

I chose to use pdm over poetry because the only custom thing from pdm is `[tool.pdm.dev-dependencies]` so it would be easy to move to another tools if need while poetry requires to use non standard `[tool.poetry.project]` etc.

pyproject.toml also include configuration for other tools so pylintrc and setup.cfg are no longer needed

as you can see in the makefile pdm can generate the requirement.txt files while dependencies are declared also in pyproject.toml

there is maybe some cleaning to do in dependencies because I'm not sure you are using both flake8 and pylint or that all crypto runtime dependencies are really used

### CODE REVIEW

**Comment by n3rada** [comment]
Hello there, is `ldeep` still maintained?

**Comment by BastienFaure** [comment]
It is still maintained. We are just busy at the moment but we will take a look at the issues and PRs. We are more likely to close of all of them once of twice a year that working on them as they come in.

**Comment by n3rada** [comment]
Fair enough. Thus, I can work on enhancements or ideas for your good project, could I? 

Could you just fast review this one tho'? Because it is tremendously important for developers to have a proper `poetry` usable environment.

**Comment by BastienFaure** [comment]
I will do it the week of May 13-19th, I am unavailable until then. You have my word. You can work on whatever we want, this project lives mostly because of collaboration :)

**Comment by BastienFaure** [comment]
@noraj You PR looks good. I am on the way of merging it. Looking at it made me realize that I wasn't leveraging actions properly and I am trying to adapt the build process to build cross-platforms executable. I have good hope to make substantial changes over the weekend and have it merged. Later on we can look at the requirements and shrink them.

**Pull request merged**
